export const USER_REGISTRATION_CREATED = "USER_REGISTRATION_CREATED";
export const USER_LOGIN_CREATED = "USER_LOGIN_CREATED";
export const FETCH_MEMORIES_DATA = "FETCH_MEMORIES_DATA";
export const STORE_USER_DATA = "STORE_USER_DATA";
